import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Clock, BookOpen, ArrowLeft, Loader2, CheckCircle2 } from 'lucide-react';
import { Card } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { Badge } from '../../components/ui/Badge';
import { Breadcrumb } from '../../components/layout/Breadcrumb';
import { courseService } from '../../services/courseService';
import { lessonService } from '../../services/lessonService';
import { useToast } from '../../hooks/useToast';

export default function CourseDetails() {
 const {id}=useParams(); const [course,setCourse]=useState(null); const [lessons,setLessons]=useState([]); const [enrollment,setEnrollment]=useState(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const {addToast}=useToast();
 const load=async()=>{setLoading(true); const [c,l,m]=await Promise.allSettled([courseService.getCourse(id),courseService.getLessons(id),courseService.getEnrolled()]); if(c.status==='fulfilled')setCourse(c.value.data); if(l.status==='fulfilled')setLessons(l.value.data||[]); if(m.status==='fulfilled')setEnrollment((m.value.data||[]).find(e=>e.course.id===Number(id))||null); setLoading(false)};
 useEffect(()=>{load()},[id]);
 const enroll=async()=>{setBusy(true);try{await courseService.enroll(id);addToast('Course enrolled successfully','success');await load()}catch(e){addToast(e.response?.data?.detail||'Enrollment failed','error')}finally{setBusy(false)}};
 if(loading)return <div className="py-20 text-center text-slate-500"><Loader2 className="animate-spin mx-auto"/></div>; if(!course)return <div className="text-slate-400">Course not found.</div>;
 const image=course.thumbnail_url || (course.level==='advanced'?'/course-art/advanced.svg':course.level==='intermediate'?'/course-art/vocabulary.svg':'/course-art/alphabet.svg');
 return <div className="max-w-5xl mx-auto space-y-6"><Breadcrumb items={[{label:'Courses',path:'/courses'},{label:course.title}]}/><Link to="/courses" className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-200"><ArrowLeft size={16}/> Back to courses</Link><div className="rounded-2xl border border-slate-800 bg-[#151a24] overflow-hidden"><div className="relative h-64 lg:h-80"><img src={image} alt={course.title} className="w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#0b1018] via-transparent to-transparent"/><div className="absolute bottom-0 p-7"><Badge variant="primary" className="mb-3">{course.level}</Badge><h1 className="text-3xl font-bold text-white">{course.title}</h1><div className="flex gap-4 mt-3 text-sm text-slate-300"><span className="flex items-center gap-1"><Clock size={14}/>{course.duration_minutes} min</span><span className="flex items-center gap-1"><BookOpen size={14}/>{lessons.length} lessons</span></div></div></div><div className="p-7"><p className="text-slate-400 leading-7 mb-6">{course.description || 'A structured SignSpeak learning pathway.'}</p>{enrollment&&<div className="mb-6 rounded-xl border border-slate-800 bg-[#11161f] p-4"><div className="flex justify-between text-sm"><span className="text-slate-400">Your course progress</span><strong className="text-[#20d8d3]">{enrollment.progress_percent}%</strong></div><div className="h-2 rounded-full bg-slate-800 mt-2"><div className="h-full rounded-full bg-[#16c8c4]" style={{width:`${enrollment.progress_percent}%`}}/></div></div>}<div className="flex flex-wrap gap-3">{enrollment?<Link to={lessons[0]?`/lesson/${course.id}/${lessons[0].id}`:'/courses'}><Button><BookOpen size={16}/> Continue Learning</Button></Link>:<Button onClick={enroll} loading={busy}>Enroll in Course</Button>}</div></div></div><Card><h3 className="font-semibold text-white mb-4">Course Lessons</h3><div className="space-y-3">{lessons.length?lessons.map((l,i)=><div key={l.id} className="flex items-center gap-4 rounded-xl border border-slate-800 p-4"><div className="h-9 w-9 rounded-lg bg-cyan-500/10 text-cyan-400 flex items-center justify-center text-sm font-bold">{i+1}</div><div className="flex-1"><p className="font-semibold text-slate-200">{l.title}</p><p className="text-xs text-slate-500 mt-1">{l.duration_minutes||0} min</p></div>{enrollment?<Link to={`/lesson/${course.id}/${l.id}`} className="text-sm font-semibold text-[#20d8d3]">Open</Link>:<span className="text-xs text-slate-600">Enroll to access</span>}{enrollment&&l.is_published&&<CheckCircle2 size={16} className="text-slate-700"/>}</div>):<p className="text-sm text-slate-500">No lessons have been published for this course yet.</p>}</div></Card></div>
}
